### ISSUE TITLE
Infinite recursion issue

### ISSUE THREAD

**Issue by nicksellen** [karrot-dev/karrot-frontend#2512] opened 2022-03-01 10:52 UTC
When visiting https://karrot.world/#/group/191/place/1448/activities/183343/detail in firefox I get this:

![toomuchrecursion](https://user-images.githubusercontent.com/31616/156155774-5ca640ce-75ce-4249-a522-5e513ee6f452.png)

![recusrionrouteisundefined](https://user-images.githubusercontent.com/31616/156155799-ffec7e6b-ebf1-4f28-a8fa-42ceb8b0d823.png)

That points to this line:

```js
hasView:function(){var t=this.$route.matched.length>0&&this.$route.matc
```

... in chrome it doesn't has the issue, but also doesn't open the conversation, just goes to the group wall....

**Comment by nicksellen** [comment] 2022-03-15 21:48
Mobile view I think! (And hey!)

**Comment by pogopaule** [comment] 2022-03-19 18:21
Can't reproduce it on master. I guess it has been fixed https://github.com/karrot-dev/karrot-frontend/pull/2501. I close this ticket.

**Closed by pogopaule** 2022-03-19 18:21 UTC
Labels: bug, frontend

**Comment by nicksellen** [comment] 2022-03-21 09:44
Ah, thanks, sorry for that!

**Comment by pogopaule** [comment] 2022-03-21 11:45
No worries! Was an easy bugfix for me 😄 

BTW saw you in a documentary!

**Comment by nicksellen** [comment] 2022-03-21 12:01
> BTW saw you in a documentary!

Oh, do share more! I don't know if I know about this...

**Comment by pogopaule** [comment] 2022-03-21 12:24
Starting at minute 18.30 https://www.ardmediathek.de/video/Y3JpZDovL3N3ci5kZS9hZXgvbzE1OTY3MzM/
